### PR TITLE
Improve .sources.sh and .bashrc

### PR DESCRIPTION
**Pull request by tricantivu**
Hello! I made some changes to avoid repeating the usage of echo and mkdir.

This project really caught my eye and I hope it grows even more 😃 .

Thanks.

### CODE REVIEW

**Comment by ajstrongdev** [comment]
Thank you for your pull request. I will need to do some testing on this and due to my busy schedule at the moment it will likely not be included in release 2022.04.14. I will test it after the release of 2022.04.14!

**Comment by ajstrongdev** [comment]
I've decided to do some testing now whilst I am free. If it works as intended I will merge the PR and incorporate it into 2022.04.14

**Comment by ajstrongdev** [comment]
So I've done some testing and what I've found is that the .sources.sh script and .bashrc work perfectly fine. We would require you to add an additional line to the .bashrc for rhino-config.

```sh
# Rhino aliases
alias rhino-init="mkdir ~/.rhino && mkdir ~/.rhino/updates && mkdir ~/.rhino/config && touch ~/.rhino/updates/configuration && sudo bash ~/.sources.sh && sudo apt update && sudo apt upgrade -y"
alias rhino-update="mkdir ~/rhinoupdate && mkdir ~/rhinoupdate/kernel && mkdir ~/rhinoupdate/script/ && git clone https://github.com/rollingrhinoremix/rhino-update ~/rhinoupdate/script && bash ~/rhinoupdate/script/update.sh && rm -rf ~/rhinoupdate"
alias rhino-config="mkdir ~/.rhino/config/config-script && git clone https://github.com/rollingrhinoremix/rhino-config ~/.rhino/config/config-script/ && python3 ~/.rhino/config/config-script/config.py && rm -rf ~/.rhino/config/config-script"
```

**Comment by tricantivu** [comment]
Great to hear!

I will add that alias as soon as possible.

**Comment by tricantivu** [comment]
Line with alias added.

**Comment by ajstrongdev** [comment]
Excellent, thank you for submitting it. I will test it out tomorrow.

**Pull request merged**
